# Generated by Django 3.2.4 on 2022-03-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Superuser_user'), ('2', 'teacher'), ('3', 'Student')], max_length=20),
        ),
    ]
